<?php
use files\viewerModel\padrao;
use files\viewerModel\html;
use application\libs\widgets; 
use application\libs\form;
use \files\menu\padrao as menu_padrao;
use files\database\qTipo_entidade;
use files\staGrid\gTipo_entidade;
use files\lib\auth;
    $qEnti = new qTipo_entidade();
    $Model = $qEnti->model();
    $f = new form();
	$viewer = new padrao();
	$m = new menu_padrao();
    $viewer->menu = $m->menu;
	$viewer->addLogoDefault();
    $gtentid = new gTipo_entidade();
    
$body ="<div id='todo' class='row col-lg-12'>";
$body .="<div id='cabecalio' class='col-lg-12'><h3>Cadastro de tipo de Entidade</h3></div>";
$body .="<div id='grid' class=' col-lg-12 col-lg-offset-0'>";
$body .=$gtentid->run();
$body .="</div>";
$body .="";
$body .="<form style ='display:none;' id='frmcadTipoEntidade'  class='row col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-0 col-lg-12 col-lg-offset-0'>";
$body .="<hr>";
$body .="<div class='row col-lg-6'>";
$body .= $f->divCampo("tpentidade",$Model["tpentidade"],"col-lg-12");
$body .="</div>";
$body .="<div class='row col-lg-6'>";
$body .= $f->divCampo("descricao",$Model["descricao"],"col-lg-12");
$body .="</div>";
$body .= "<div class='row col-lg-12' id='footer'>";
$body .="<hr>";
$body .="<span id='btn_login_arquiv' onclick='cadTPEntidmodal(`frmcadTipoEntidade`);' class='btn btn-primary'>Salvar</span>";
$body .="<span id='btn_limpa_arquiv' onclick='btn_limpa_form(`frmcadTipoEntidade`);' class='btn btn-sulasuccess'>Limpar</span>";
$body .="</div>";
$body .="</form><br></div>";
$body.="</div><!--fim div todo-->";

	$viewer->content = $body;
	$viewer->addClasses('scrollable docked');
	$viewer->run();